### PR TITLE
fixed missing api in the request url

### LINKED ISSUE #14: The token is not pulling notifications. It says "never used"
Even though I've created the token and set it on the Sertings, it's not working and the notifications are not dispayed.

The token says this: 
image

I have it on the config and says 0 notifications:

```[[redacted-token]]```

Even though I have notifications on github:
image

### PR DESCRIPTION
**Pull request by Logerfo**
fixes #14

### CODE REVIEW

**Comment by Logerfo** [comment]
This fix is a breaking change, since its introduction (#12) also was. An alternative would be to add the `api` in the default domain instead.

**Comment by Logerfo** [comment]
@fabiospampinato maybe we could check if the domain starts with `api.` and insert it only if it doesn't?

**Comment by fabiospampinato** [comment]
Maybe, I haven't actually had the time to take a closer look at this. The extension is working for me so I don't think this is actually the problem, but I also don't remember why I'm not querying the APIs 🤔

**Comment by Logerfo** [comment]
Pretty sure this is the problem, you can see the diff that caused it [here](https://github.com/fabiospampinato/vscode-github-notifications-bell/pull/12/files#diff-f3925b910e1692e81247fc97c15eebdd). I tested it myself and adding the `api.` worked just fine.

**Comment by fabiospampinato** [comment]
Oh yes I think that's it then! I probably haven't noticed that the extension hasn't been working for me recently as I've had the statusbar hidden.

I'm merging this then, thanks!

**Comment by mmisiarek** [comment]
It is impossible to use this extension with enterprise github that has an api under domain like such: `github.company.com/api`. Could you just use `api.github.com` as a default and point out in the documentation that whenever user wants to use custom domain they must be aware of providing not regular domain but API one?

**Comment by Logerfo** [comment]
Interesting, I didn't know about that.
Thank you for letting us now!
We probably have to face a breaking change again...

**Pull request merged**
